export default {

    ALL_COMPANY: "ALL_COMPANY",
    COMPANY_PAGE: "COMPANY_PAGE",
    ADD_COMPANY: "ADD_COMPANY",
    COMPANY_DETAIL: "COMPANY_DETAIL",
    UPDATE_COMPANY: "UPDATE_COMPANY",
    DELETE_COMANY: "DELETE_COMANY",
    COMPANY_LEVEL: "COMPANY_LEVEL",
    COMPANY_CODE: "COMPANY_CODE",

}