export default {

  MUTATE_SELECTED_EMPLOYEE_BACK_TASK_SHEET_INFO: "MUTATE_SELECTED_EMPLOYEE_BACK_TASK_SHEET_INFO",

  SEARCH_TASK_SHEET_PAGE: "SEARCH_TASK_SHEET_PAGE",

  SEARCH_BE_TASK_SHEET_PAGE: "SEARCH_BE_TASK_SHEET_PAGE",

  SEARCH_TASK_SHEET_BATCH_PAGE: "SEARCH_TASK_SHEET_BATCH_PAGE",

  SEARCH_TASK_SHEET_BATCH_SERVICE_AGREEMENT: "SEARCH_TASK_SHEET_BATCH_SERVICE_AGREEMENT",

  SEARCH_TASK_SHEET_INTEGRATE_PAGE: "SEARCH_TASK_SHEET_INTEGRATE_PAGE",

  SEARCH_TASK_SHEET_INTEGRATE_RETURN_PAGE: "SEARCH_TASK_SHEET_INTEGRATE_RETURN_PAGE",

  SEARCH_TASK_SHEET: "SEARCH_TASK_SHEET",

  SEARCH_TASK_SHEET_INTEGRATE: "SEARCH_TASK_SHEET_INTEGRATE",

  SEARCH_TASK_SHEET_INTEGRATE_RETURN: "SEARCH_TASK_SHEET_INTEGRATE_RETURN",

  SEARCH_TASK_SHEET_RETURN_EXAMINE: "SEARCH_TASK_SHEET_RETURN_EXAMINE",

  TASK_SHEET_RETURN_APPLY: "TASK_SHEET_RETURN_APPLY",

  TASK_SHEET_RETURN_REFUSE: "TASK_SHEET_RETURN_REFUSE",

  MUTATE_TASK_SHEET_PAGE: "MUTATE_TASK_SHEET_PAGE",

  MUTATE_TASK_SHEET_BATCH_PAGE: "MUTATE_TASK_SHEET_BATCH_PAGE",

  MUTATE_TASK_SHEET_BATCH_SERVICE_AGREEMENT: "MUTATE_TASK_SHEET_BATCH_SERVICE_AGREEMENT",

  MUTATE_TASK_SHEET_INTEGRATE_PAGE: "MUTATE_TASK_SHEET_INTEGRATE_PAGE",

  MUTATE_TASK_SHEET_INTEGRATE: "MUTATE_TASK_SHEET_INTEGRATE",

  MUTATE_TASK_SHEET_RETURN_PAGE: "MUTATE_TASK_SHEET_RETURN_PAGE",

  MUTATE_TASK_SHEET_RETURN_EXAMINE_PAGE: "MUTATE_TASK_SHEET_RETURN_EXAMINE_PAGE",

  MUTATE_CURRENT_PAGE: "MUTATE_CURRENT_PAGE",

  MUTATE_RETURN_CURRENT_PAGE: "MUTATE_RETURN_CURRENT_PAGE",

  MUTATE_PAGE_SIZE: "MUTATE_PAGE_SIZE",

  MUTATE_SEARCH_TASK_SHEET_PAGE: "MUTATE_SEARCH_TASK_SHEET_PAGE",

  MUTATE_SELECTION_BATCH_ALL_DATA: "MUTATE_SELECTION_BATCH_ALL_DATA",

  MUTATE_CANCEL_SELECTION_BATCH_ALL_DATA: "MUTATE_CANCEL_SELECTION_BATCH_ALL_DATA",

  MUTATE_RETURN_PAGE_SIZE: "MUTATE_RETURN_PAGE_SIZE",

  MUTATE_SEARCH_FORM: "MUTATE_SEARCH_FORM",

  MUTATE_TASK_SHEET_BATCH_SUBMIT_ITEM:"MUTATE_TASK_SHEET_BATCH_SUBMIT_ITEM",

  MUTATE_TASK_SHEET_DETAIL: "MUTATE_TASK_SHEET_DETAIL",

  MUTATE_TASK_SHEET_SOCIAL_FEE_INFO: "MUTATE_TASK_SHEET_SOCIAL_FEE_INFO",

  MUTATE_TASK_SHEET_SOCIAL_FEE_ITEM: "MUTATE_TASK_SHEET_SOCIAL_FEE_ITEM",

  MUTATE_TASK_SHEET_SOCIAL_INFO_LIST: "MUTATE_TASK_SHEET_SOCIAL_INFO_LIST",

  MUTATE_TASK_SHEET_SOCIAL_FEE_BATCH_INFO: "MUTATE_TASK_SHEET_SOCIAL_FEE_BATCH_INFO",

  MUTATE_TASK_SHEET_UNDONE_REASON: "MUTATE_TASK_SHEET_UNDONE_REASON",

  MUTATE_TASK_SHEET_HISTORY: "MUTATE_TASK_SHEET_HISTORY",

  MUTATE_TASK_SHEET_LOG_INFO: "MUTATE_TASK_SHEET_LOG_INFO",

  MUTATE_TASK_SHEET_SERVICE_AGREEMENT: "MUTATE_TASK_SHEET_SERVICE_AGREEMENT",

  MUTATE_TASK_SHEET_AF_SERVICE_PRODUCT: "MUTATE_TASK_SHEET_AF_SERVICE_PRODUCT",

  MUTATE_SERVICE_PRODUCT_BY_TASK_SHEET_CITY: "MUTATE_SERVICE_PRODUCT_BY_TASK_SHEET_CITY",

  MUTATE_TASK_SHEET_SERVICE_PRODUCT: "MUTATE_TASK_SHEET_SERVICE_PRODUCT",

  MUTATE_TASK_SHEET_EMPLOYEE_INFO: "MUTATE_TASK_SHEET_EMPLOYEE_INFO",

  MUTATE_TASK_SHEET_BE_EMPLOYEE_INFO: "MUTATE_TASK_SHEET_BE_EMPLOYEE_INFO",

  GET_TASK_SHEET_DETAIL: "GET_TASK_SHEET_DETAIL",

  GET_TASK_SHEET_BE_EMPLOYEE_INFO: "GET_TASK_SHEET_BE_EMPLOYEE_INFO",

  GET_TASK_SHEET_SOCIAL_FEE_INFO: "GET_TASK_SHEET_SOCIAL_FEE_INFO",

  GET_TASK_SHEET_SOCIAL_INFO_LIST: "GET_TASK_SHEET_SOCIAL_INFO_LIST",

  GET_TASK_SHEET_SOCIAL_FEE_BATCH_INFO: "GET_TASK_SHEET_SOCIAL_FEE_BATCH_INFO",

  GET_TASK_SHEET_UNDONE_REASON: "GET_TASK_SHEET_UNDONE_REASON",

  GET_TASK_SHEET_HISTORY: "GET_TASK_SHEET_HISTORY",

  GET_TASK_SHEET_LOG_INFO: "GET_TASK_SHEET_LOG_INFO",

  GET_TASK_SHEET_SERVICE_AGREEMENT: "GET_TASK_SHEET_SERVICE_AGREEMENT",

  GET_TASK_SHEET_AF_SERVICE_PRODUCT: "GET_TASK_SHEET_AF_SERVICE_PRODUCT",

  GET_SERVICE_PRODUCT_BY_TASK_SHEET_CITY: "GET_SERVICE_PRODUCT_BY_TASK_SHEET_CITY",

  GET_TASK_SHEET_SERVICE_PRODUCT: "GET_TASK_SHEET_SERVICE_PRODUCT",

  GET_TASK_SHEET_EMPLOYEE_INFO: "GET_TASK_SHEET_EMPLOYEE_INFO",

  MUTATE_TASK_SHEET_SERVICE_PRODUCT_AMOUNT: "MUTATE_TASK_SHEET_SERVICE_PRODUCT_AMOUNT",

  MUTATE_TASK_SHEET_SERVICE_PRODUCT_CHANGE: "MUTATE_TASK_SHEET_SERVICE_PRODUCT_CHANGE",

  DELETE_TASK_SHEET_SERVICE_PRODUCT: "DELETE_TASK_SHEET_SERVICE_PRODUCT",

  SUBMIT_TASK_SHEET: "SUBMIT_TASK_SHEET",

  SUBMIT_TASK_SHEET_BATCH: "SUBMIT_TASK_SHEET_BATCH",

  MUTATE_SUBMIT_SERVICE_AGREEMENT_TYPE: "MUTATE_SUBMIT_SERVICE_AGREEMENT_TYPE",

  MUTATE_SUBMIT_SERVICE_AGREEMENT_ID: "MUTATE_SUBMIT_SERVICE_AGREEMENT_ID",

  MUTATE_SUBMIT_BATCH_SERVICE_AGREEMENT_ID: "MUTATE_SUBMIT_BATCH_SERVICE_AGREEMENT_ID",

  MUTATE_SUBMIT_ENTRUST_REMARK: "MUTATE_SUBMIT_ENTRUST_REMARK",

  MUTATE_SUBMIT_ENTRUST_RETREAT_REASON: "MUTATE_SUBMIT_ENTRUST_RETREAT_REASON",

  BACK_TASK_SHEET_TO_AF: "BACK_TASK_SHEET_TO_AF",

  BACK_TASK_SHEET_BATCH_TO_AF: "BACK_TASK_SHEET_BATCH_TO_AF",

  DOWNLOAD_TASK_SHEET_LIST: "DOWNLOAD_TASK_SHEET_LIST",

  GET_SOCIAL_SECURITY_DETAILS: "GET_SOCIAL_SECURITY_DETAILS",

  UPDATE_ACCEPT_ENTRUST: "UPDATE_ACCEPT_ENTRUST",

  MUTATE_SOCIAL_SECURITY_DETAILS: "MUTATE_SOCIAL_SECURITY_DETAILS",

  GET_GOL_DATA: "GET_GOL_DATA",

  MUTATE_GOL_DATA: "MUTATE_GOL_DATA",

  MUTATE_SUBMIT_BE_ENTRUST_REMARK: "MUTATE_SUBMIT_BE_ENTRUST_REMARK",

  IDENTIFY_EMPLOYEES: "IDENTIFY_EMPLOYEES",

  UPDATE_END_TASKSHEETDETAIL: "UPDATE_END_TASKSHEETDETAIL",

  GET_SERVICE_ORGANIZATION_AGREEMENT: "GET_SERVICE_ORGANIZATION_AGREEMENT"
}
