export default {

  SUBMIT_EMPLOYEE_BACK_TASK_SHEET: "SUBMIT_EMPLOYEE_BACK_TASK_SHEET",

  BACK_SERVICE_CONFIRM_BACK_TASK_SHEET: "BACK_SERVICE_CONFIRM_BACK_TASK_SHEET",

  BACK_COMMISSIONER_CONFIRM_BACK_TASK_SHEET: "BACK_COMMISSIONER_CONFIRM_BACK_TASK_SHEET",

  BACK_TASK_SHEET_TO_FRONT: "BACK_TASK_SHEET_TO_FRONT",

  MUTATE_SELECTED_EMPLOYEE_BACK_TASK_SHEET_INFO: "MUTATE_SELECTED_EMPLOYEE_BACK_TASK_SHEET_INFO",

  MUTATE_CURRENT_PAGE: "MUTATE_CURRENT_PAGE",

  MUTATE_PAGE_SIZE: "MUTATE_PAGE_SIZE",

  MUTATE_SEARCH_FORM: "MUTATE_SEARCH_FORM",

  MUTATE_GET_EMPLOYEE_BACK_TASK_SHEET_DETAIL: "MUTATE_GET_EMPLOYEE_BACK_TASK_SHEET_DETAIL",

  MUTATE_SUBMIT_BACK_TASK_SHEET_RETREAT_REASON: "MUTATE_SUBMIT_BACK_TASK_SHEET_RETREAT_REASON",

  MUTATE_SEARCH_TASK_SHEET_PAGE: "MUTATE_SEARCH_TASK_SHEET_PAGE",

  GET_EMPLOYEE_BACK_TASK_SHEET_DETAIL: "GET_EMPLOYEE_BACK_TASK_SHEET_DETAIL",

  SEARCH_TASK_SHEET_PAGE: "SEARCH_TASK_SHEET_PAGE"

}
