export default {

  SEARCH_EMPLOYEE_TASK_SHEET_PAGE: "SEARCH_EMPLOYEE_TASK_SHEET_PAGE",

  MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PAGE: "MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PAGE",

  MUTATE_EMPLOYEE_TASK_SHEET_PAGE_SIZE: "MUTATE_EMPLOYEE_TASK_SHEET_PAGE_SIZE",

  MUTATE_EMPLOYEE_TASK_SHEET_CURRENT_PAGE: "MUTATE_EMPLOYEE_TASK_SHEET_CURRENT_PAGE",

  MUTATE_SELECTED_EMPLOYEE_TASK_SHEET_INFO: "MUTATE_SELECTED_EMPLOYEE_TASK_SHEET_INFO",

  SAVE_EMPLOYEE_INFO: "SAVE_EMPLOYEE_INFO",

  SEARCH_EMPLOYEE_INFO: "SEARCH_EMPLOYEE_INFO",

  SAVE_EMPLOYEE_TASK_SHEET_INFO: "SAVE_EMPLOYEE_TASK_SHEET_INFO",

  MUTATE_ADD_EMPLOYEE_INFO: "MUTATE_ADD_EMPLOYEE_INFO",

  MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PARAM: "MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PARAM",

  MUTATE_SEARCH_EMPLOYEE_INFO: "MUTATE_SEARCH_EMPLOYEE_INFO",

  GET_EMPLOYEE_TASK_SHEET_DETAIL: 'GET_EMPLOYEE_TASK_SHEET_DETAIL',
  MUTATE_GET_EMPLOYEE_TASK_SHEET_DETAIL:'MUTATE_GET_EMPLOYEE_TASK_SHEET_DETAIL',

  GET_EMPLOYEE_TASK_SHEET_SOCIAL_FEE_SEGMENT: 'GET_EMPLOYEE_TASK_SHEET_SOCIAL_FEE_SEGMENT',
  MUTATE_GET_EMPLOYEE_TASK_SHEET_SOCIAL_FEE_SEGMENT:'MUTATE_GET_EMPLOYEE_TASK_SHEET_SOCIAL_FEE_SEGMENT',

  GET_EMP_TASK_SHEET_EMPLOYEE_INFO: 'GET_EMP_TASK_SHEET_EMPLOYEE_INFO',
  MUTATE_GET_EMP_TASK_SHEET_EMPLOYEE_INFO:'MUTATE_GET_EMP_TASK_SHEET_EMPLOYEE_INFO',
}
