export default {

  SEARCH_EMPLOYEE_TASK_SHEET_PAGE: "SEARCH_EMPLOYEE_TASK_SHEET_PAGE",

  MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PAGE: "MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PAGE",

  MUTATE_EMPLOYEE_TASK_SHEET_PAGE_SIZE: "MUTATE_EMPLOYEE_TASK_SHEET_PAGE_SIZE",

  MUTATE_EMPLOYEE_TASK_SHEET_CURRENT_PAGE: "MUTATE_EMPLOYEE_TASK_SHEET_CURRENT_PAGE",

  SAVE_EMPLOYEE_INFO: "SAVE_EMPLOYEE_INFO",

  EMPLOYEE_PAGE: "EMPLOYEE_PAGE",

  QUERY_EMPLOYEE_ID: "QUERY_EMPLOYEE_ID",

  UPDATE_EMPLOYEE_INFO: "UPDATE_EMPLOYEE_INFO",

  EMPCOMPANY_PAGE: "EMPCOMPANY_PAGE"

}
