export default {

  SEARCH_EMPLOYEE_TASK_SHEET_PAGE: "SEARCH_EMPLOYEE_TASK_SHEET_PAGE",

  MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PAGE: "MUTATE_SEARCH_EMPLOYEE_TASK_SHEET_PAGE",

  MUTATE_EMPLOYEE_TASK_SHEET_PAGE_SIZE: "MUTATE_EMPLOYEE_TASK_SHEET_PAGE_SIZE",

  MUTATE_EMPLOYEE_TASK_SHEET_CURRENT_PAGE: "MUTATE_EMPLOYEE_TASK_SHEET_CURRENT_PAGE",
}
