export default {

  SEARCH_SOCIAL_POLICY_BY_PARAM: "SEARCH_SOCIAL_POLICY_BY_PARAM",
  MUTATE_SEARCH_SOCIAL_POLICY_BY_PARAM: "MUTATE_SEARCH_SOCIAL_POLICY_BY_PARAM",

  MUTATE_SOCIAL_POLICY_PARAM_CHANGE: "MUTATE_SOCIAL_POLICY_PARAM_CHANGE",
}
